version: '3'
services:
  # Service de l'application Rails
  web:
    image: ruby:3.0 # Utilisez l'image Ruby appropriée
    container_name: my_rails_app
    volumes:
      - .:/app
    ports:
      - "3000:3000" # Port pour l'application Rails
    environment:
      RAILS_ENV: development
      DATABASE_URL: sqlite3:///app/db/development.sqlite3  # URL de la base de données SQLite